steps:
  - imports:
      # Only align the imports per group (a groups is formed by adjacent
      # import lines).
      align: group
      list_align: after_alias
      pad_module_names: false
      long_list_align: new_line_multiline
      empty_list_align: inherit
      list_padding: 4
      separate_lists: true
      space_surround: false

  - language_pragmas:
      style: compact # diff-safe
      align: true
      remove_redundant: true

  - trailing_whitespace: {}

columns: 80 # default
newline: native

language_extensions:
  - ApplicativeDo
  - FlexibleContexts
  - FlexibleInstances
  - OverloadedStrings
  - TypeFamilies